[project]
name = "dz1-analytics-of-the-streaming-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dmitriy", email = "fdu1287@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
dz1-analytics-of-the-streaming-service = "dz1_analytics_of_the_streaming_service:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]
